### PR TITLE
Update testrig

### PR DESCRIPTION
**Pull request by dodozean**
After creating your pull request, tick these boxes if they are applicable to you.

- [ ] I have tested my changes against the `dev` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x] I have tested my changes on Python 3.8 or higher
- [x] I have ensured my code is formatted using [Black](https://github.com/psf/black)

----

### Description

- Implement the queue and buffering mechanism for test commands

- Test thoroughly with Python 3.10/3.12/3.13, no Python-version related issue is found

- Add a coverage report of the latest version of testrig in htmlcov/, the original line coverage of testrig is 58%, the one of updated testrig is 60%

- Remove an inaccessible url from PLAYABLE_STRING_ARRAY, and add a small spotify playlist as well as a youtube livestream link into it

- Add a filtering function to filter the PLAYABLE_STRING_ARRAY before testing them on certain commands (like ``stream`` and ``pldump``)

- Remove redundant testing commands (like ``repeat off``) and refine them

- Add commands before some certain tests to ensure deterministic behavior (like ``seek`` and ``setspeed``)

- Add config change commands before testing certain commands (like ``setprefix`` and ``cache clear``)

- Remove deprecated command ``option``

### Related issues (if applicable)

Python 3.13 support #2435

### CODE REVIEW

**Comment by dodozean** [comment]
@itsTheFae If there are any changes you want us to make, feel free to let us know! Also, if you do not want the coverage report to appear in the repo, I can delete it from the pr and send it to you in other ways.

**Comment by itsTheFae** [comment]
Regarding the coverage report files.  If you don't mind, could you PR the report files against the `fae` branch of this repo?  
The two branches are almost identical, and it will keep the extra files out of the upstream PR until we can touch base with the owners about perhaps putting coverage reports on the gh-pages site.

**Comment by dodozean** [comment]
I've changed the target branch and also solved the conflicts.

**Comment by dodozean** [comment]
Sorry, do you mean I should create a separate PR targeting fae branch that only contains the coverage report or just switch the targeting branch of this PR to fae? I might have misunderstanded your message. If I did, I will revert the current commit and make a separate PR.

**Comment by YijunWang1121** [comment]
The attached logs contain the results of test suites run on different Python versions for your reference.

[python10_ubuntu.log](https://github.com/user-attachments/files/18070605/python10_ubuntu.log)
[python12_macos.log](https://github.com/user-attachments/files/18070606/python12_macos.log)
[python13_ubuntu.log](https://github.com/user-attachments/files/18070607/python13_ubuntu.log)

**Comment by itsTheFae** [comment]
> Sorry, do you mean I should create a separate PR targeting fae branch that only contains the coverage report or just switch the targeting branch of this PR to fae? I might have misunderstanded your message. If I did, I will revert the current commit and make a separate PR.

Yes, I meant make a separate PR for the coverage reports and remove them from this PR.  Sorry for the confusion there. 
Thank you for your time and testing!

**Comment by dodozean** [comment]
Gotcha! I have cleaned these things up for this PR, @YijunWang1121 will make a separate PR with the coverage report.

**Comment by itsTheFae** [comment]
Thanks again!

**Pull request merged**
